### ISSUE TITLE
Hello....

### ISSUE THREAD

**Issue by AlexPads** [LamPocketVN/LpkPointShopUI#2]
I would have really liked you to have forked my plugin first on GitHub before just downloading and modifying. 
please put a link to the original in the ReadMe thanks I would recommend doing the same for your "PointAPI" 
Here is a link to the original thanks for the interest!
https://github.com/AlexPads/ShopUI-FormAPI-Working
Also add yourself as an author don't change the author entirely otherwise its stealing :3

**Comment by LamPocketVN** [comment]
Thanks for your help :D
