### ISSUE TITLE
HeLp

### ISSUE THREAD

**Issue by 2cool4u567** [LamPocketVN/LpkPointShopUI#3]
How do i use, and how do i open the shop, /shop doesnt work

**Comment by AlexPads** [comment]
@2cool4u567 He changed the command to /pshop 
I would suggest using the Original plugin CustomShopUI from Poggit.
https://poggit.pmmp.io/p/CustomShopUI/4.0.5
His "PointAPI" is just EconomyAPI but he changed the name this guy is not a dev don't trust them!
Thanks!
